### ISSUE TITLE
User Interface consistency

### ISSUE THREAD

**Issue by Sebastian-Jung** [thenlevy/ensnano#13]
[Tested in `dev`]
There are some inconsistencies in the way the user interface is designed:

* Nucleotide selection:
    * In 3D View one can select a nucleotide/cross-over which is then highlighted, but not highlighted in the 2D View (except when clicking on bonds between nucleotides)
    * In 2D View one can select a single nucleotide and it is  highlighted in 3D View but not in 2D View
    -> Request: Make nucleotides highlighted/selectable in 2D View  
* Nucleotide focusing on other view:
    * I double *right* click on a nucleotide/cross-over in 2D View -> I center nudleotide/cross-over in 3D view
    * If trying the same on a nucleotide in 3D View, 2D View doesn't change
    * One can only jump from 3D View to 2D View if double *left* clicked 
    -> Request: Make centering in different view consistent (Same mouse button/key) and allow nucleotide and cross-over centering for both views
* Nucleotide highlight (Bug?):
    * Moving the mouse in the 2D view over some nucleotides highlights them in the 3D View in green
    * Moving the mouse in 3D view doesn't show any hints in the 2D View (Might be a bug since it was presented in the [YouTube Video](https://youtu.be/HcIdXRqyceE?list=PLMpoApdWXUWbozBJD3poFrU0KZxK2--9g&t=194))

I think in general it might be good to have a way to highlight/select/focus single nucleotides in the 2D View, this would the allow to have a symmetric behavior from 2D and 3D view.

**Comment by thenlevy** [comment]
We should indeed highlight selected/hovered nucleotides in the 2D view.
Regarding the right click left click inconsistencies we should indeed think of a more intuitive mapping from mouse event to actions

**Comment by thenlevy** [comment]
I've started working on a new interface for the 2D view. It is available on the branch `remap_clicks`. The difference between this new interface and the current one is that the behavior of mouse buttons are changed.

- Left Clicking on a nucleotide selects it, clicking again selects the strands on which the nucleotide lies
- Right Clicking on a nucleotide cuts the strands at that position, or merge it with the neighboring strand (this was the previous behavior of Left Clicking on a nucleotide)
- Double Left clicking on a nucleotide center the nucleotide in the 3D view (previously this was done by double right clicking)

This probably won't be in the next release because I think these kind of changes need some time to mature a bit, and we want to release soon because of #15

**Comment by thenlevy** [comment]
I have pushed the new interface to `dev`. We will include it in the next release
