### ISSUE TITLE
Saving opened cadnano file will overwrite file

### ISSUE THREAD

**Issue by Sebastian-Jung** [thenlevy/ensnano#15]
This might not be a bug but it can be really bad for new users.
How to reproduce:
* Open ensnano
* Load a .json file created by cadnano
* Click Ctrl+S or Save the file
* Expected: Ask for new location/filename since the file wasn't saved in a .ens format before
* What actually happens: The location and name of the cadnano file is taken as the path to the file. Saving the design will overwrite the .json cadnano file. This will destroy the file and one cannot load the file back into cadnano since the formats are not compatible, which might be a big problem for some users.

**Comment by thenlevy** [comment]
That's the intended behavior but I agree that it should be changed. I did not realize that user could lose their cadnano file because of it.

**Comment by Sebastian-Jung** [comment]
Maybe an explicit `Import` function in addition to `Open` might be useful, this would also allow importing multiple files (from cadnano, scadnano) in one ensnano session.

**Comment by thenlevy** [comment]
I've pushed a path to the `dev` branch that fixes this problem. What it does is that a new file name is asked when saving if the current file name does not have the `.ens` extension. 

Since this is quite critical we will  soon release binaries that include this patch.

Regarding the import of multiple designs into one single ENSnano session, I agree that this can be useful, I will create a specific issue for that: #17
