### ISSUE TITLE
oxDNA export 

### ISSUE THREAD

**Issue by zoombya** [thenlevy/ensnano#3]
The exported structure has no base-pairing in oxDNA and many overlaps.
![image (8)](https://user-images.githubusercontent.com/1756978/121941957-c5fa2380-cd04-11eb-98dd-be7d372fe1ba.png)
![image (7)](https://user-images.githubusercontent.com/1756978/121941969-c8f51400-cd04-11eb-9e8e-4d54534d41dc.png)
Taco oxDNA converted file for reference:
![canvas (66)](https://user-images.githubusercontent.com/1756978/121942183-0e194600-cd05-11eb-9490-a8debe69b251.png)
![canvas (65)](https://user-images.githubusercontent.com/1756978/121942193-0fe30980-cd05-11eb-811c-f01f09080b08.png)

**Comment by thenlevy** [comment]
Thank you for reporting this.

Is this a designed imported from `cadnano` to `ENSnano`, and then converted from `ENSnano` to `oxDNA` ? In that case the problem might be that `ENSnano` does not position correctly the helices during the import from `cadnano`. In that case the overlapping should also be visible in the 3D view of `ENSnano`.

Could you provide the `cadnano` file ?

**Comment by zoombya** [comment]
Here is a simplified test tile, from cadnano SQ 
I'm using the windows version of ensnano.
[test_tile.zip](https://github.com/thenlevy/ensnano/files/6664518/test_tile.zip)

**Comment by thenlevy** [comment]
I loaded your example and I think the problem could actually be due to the fact that I missunderstood the oxDNA format. 

In the oxDNA configuration file, a position for each nucleotide must be given. I thought that this position were the "backbone position" (position of the sugar) , while it might actually be the position of the base.

ENSnano is therefore producing oxDNA files in which the radius of the helices is too large. This should not be too difficult to fix.

**Comment by thenlevy** [comment]
It actually seems that the position that must be written in the cofinguration file is neither that of the backbone nor that of the base, but the position of the center of mass.
I found the formula to convert backbone position to center of mass position in taco oxDNA.

Could you check on the branch `fix_oxdna_export` if the export now look correct to you ?
Here is a compiled executable for windows of that branch 
[ensnano_fix_oxdna_export.zip](https://github.com/thenlevy/ensnano/files/6665673/ensnano_fix_oxdna_export.zip)

**Comment by zoombya** [comment]
Hi, thanks for the quick reply and effort. 
You are much closer now, but you most likely have a problem with the a-vectors. 
Possibly  ox-views / Dynamics / Forces / Create from Base pairs feature might be of help to you.
It creates Force traps between bases which are connected, but fails on the test structure. 

Also this colab lets you run an online instance of oxDNA so you can check if the design explodes. (with this design
forces are needed). https://colab.research.google.com/drive/1nFC9zy-wEwwl8vlJZAbQZZofavP4PXvL#scrollTo=C_8TB2t5gxDg

**Comment by thenlevy** [comment]
I think I have fixed the problem with the a-vectors.
The problem was that for the vector `a1` I used the backbone to helix axis vector, while I needed the backbone to base vector. 
I have been able to use the colab to run a simulation of the design exported with ENSnano

I will post today a compiled executable for windows of the patched version

**Comment by zoombya** [comment]
great thanks ;)

**Comment by thenlevy** [comment]
fixed by #6
